# Generated by Django 3.1.2 on 2021-06-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
