# Generated by Django 3.1.2 on 2021-06-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210604_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='qty',
            field=models.CharField(max_length=100),
        ),
    ]
