# Generated by Django 3.1.2 on 2021-05-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='city',
        ),
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
        migrations.AddField(
            model_name='data',
            name='number1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='number2',
            field=models.IntegerField(default=42),
        ),
    ]
